Tons of Optimizations
create-juicey-app/wantyougone pull request #2
Opened 2024-02-19 12:00 UTC by cloudcloudskies

Removed a lot clutter and comments
Removed lyrics generator thing
Changed wyg.mp3 with original Want You Gone
Better WantYouGone.py

2024-02-21 09:32 UTC, create-juicey-app commented
Thats a lil wierd, i still want the generator to be here because i want other people to make their own creations with my project. currently seeing what you did there, but thank you a lot for supporting my code

2024-02-21 09:38 UTC, create-juicey-app commented
reviewed most of the changes, not sure if i should merge, theres good and bad features added like the lyrics.txt changes, i dont like them, as they dont give credit to the original creators, and WYGgenerator being removed..

2024-02-21 09:39 UTC, create-juicey-app requested changes
need changes

2024-02-21 09:39 UTC, create-juicey-app commented on WantYouGone.py
hmm, seems better

2024-02-21 09:39 UTC, create-juicey-app commented on lyrics.txt
what

2024-02-21 11:11 UTC, cloudcloudskies commented
give me a list of changes you want

2024-02-21 11:33 UTC, cloudcloudskies commented
I did some general optimization and did things you want

2024-02-24 14:26 UTC, MrUbun2 commented
why were the code comments removed?

2024-02-24 15:07 UTC, create-juicey-app commented
thats better, but please. dont remove code parts that seems "unessesary" like `os.environ['PYGAME_HIDE_SUPPORT_PROMPT'] = "hide"`, this WILL break the gui version.

2024-02-24 19:01 UTC, cloudcloudskies commented
ok ima add it again

2024-02-24 19:18 UTC, cloudcloudskies commented
> why were the code comments removed?

thats the point btw

2024-02-25 04:31 UTC, MrUbun2 commented
> > why were the code comments removed?
> 
> 
> 
> thats the point btw

but then its less readable 😭

2024-02-25 05:42 UTC, cloudcloudskies commented
yes

2024-02-27 10:25 UTC, create-juicey-app commented
yea, im gonna review that

2024-02-27 11:02 UTC, cloudcloudskies commented
okay

2024-02-28 20:41 UTC, create-juicey-app commented
Currently testing the code, can refine or remake the part that explained people can make their own lyrics with this project?

2024-02-28 22:00 UTC, create-juicey-app requested changes

2024-02-28 22:00 UTC, create-juicey-app commented on LICENSE
Keep it!

2024-02-28 22:00 UTC, create-juicey-app commented on README.md
Add back the syntax

2024-02-28 22:00 UTC, create-juicey-app commented on WantYouGone.py
Meh, minor changes, but okay

2024-02-28 22:00 UTC, create-juicey-app commented on requirements.txt
Really good

2024-02-28 22:00 UTC, create-juicey-app commented on lyrics.txt
Meh, but ok

2024-02-29 12:26 UTC, cloudskies13 commented
TODOS:
Fix GUI, disable that 01010101110 thing
Change the font to arial bold

2024-03-16 06:41 UTC, cloudcloudskies commented
oops i broke the entire thing 💀

2024-03-20 08:15 UTC, create-juicey-app commented
ouch

2024-03-20 11:22 UTC, cloudcloudskies commented
ngl yes

2024-03-20 11:23 UTC, cloudcloudskies commented
gui version needs fix, didnt tested the normal ver

2024-03-31 18:47 UTC, cloudcloudskies commented
u merged all prs except this

2024-04-11 21:21 UTC, create-juicey-app commented
I'm gonna try to incorporate this on an experimental branch

2024-04-11 21:41 UTC, create-juicey-app commented
no shit github is so fucking scary, one mistake and your main gets fucked up 😭

2024-04-11 21:45 UTC, merged

2024-04-11 21:46 UTC, create-juicey-app commented
PHEW, im relieved, time to get that deserved sleep (i need to fix my sleep schedule.)

2024-04-12 06:38 UTC, cloudcloudskies commented
lol ty for merging after years

2024-04-13 07:10 UTC, create-juicey-app commented
> lol ty for merging after years

sorry, i spent too much time chomping on uranium

2024-04-13 09:30 UTC, cloudcloudskies commented
npnp, do u have discord

2024-04-16 07:12 UTC, create-juicey-app commented
> npnp, do u have discord

joober97